name: Datapy
channels:
  - conda-forge
  - defaults
dependencies:
  # Principais bibliotecas
  - python=3.12.3
  - numpy=2.1.0
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - matplotlib=3.9.1
  - seaborn=0.13.2
  - jupyterlab=4.2.4

  # Ferramentas de desenvolvimento
  - flake8=7.0.0
  - autopep8=2.2.0
  - pylint=3.2.6
  - black
  - isort=5.13.2

  # Dependências de suporte
  - pip
  - pip:
      - jupyterlab-cell-flash==0.4.0
      - jupyterlab-spellchecker==0.8.4
      - yapf==0.40.2

  # Outras dependências
  - zlib=1.3.1
  - readline=8.2
  - openssl=3.3.1

  # Dependências para visualização e formatação
  - ipywidgets=8.1.3
  - matplotlib-inline=0.1.7
